project_id = "vntkvhmpnvnqxdprgvjk"

[functions.gmail-oauth]
verify_jwt = true

[functions.sync-messages]
verify_jwt = false

[functions.send-reply]
verify_jwt = true

[functions.setup-gmail-watches]
verify_jwt = true

[functions.gmail-webhook]
verify_jwt = false

[functions.renew-gmail-watches]
verify_jwt = true